name: Build and deploy .NET 8 Web API to Azure Web App - bizflow-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código-fonte
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configura a versão do .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restaurar dependências do projeto
      - name: Restore dependencies
        run: dotnet restore src/WebAPI/WebAPI.csproj

      # Build do projeto
      - name: Build the project
        run: dotnet build --configuration Release src/WebAPI/WebAPI.csproj

      # Publicação do projeto
      - name: Publish the project
        run: dotnet publish --configuration Release --output ./publish src/WebAPI/WebAPI.csproj

      # Logar no Azure para o deploy
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Deploy para o Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bizflow-api'
          slot-name: 'production'
          package: ./publish
